docs: drop overworks, fix for typescript 7
tsconfig.json(10,5): error TS5102: Option 'baseUrl' has been removed. Please remove it from your configuration.
  Use '"paths": {"*": ["./*"]}' instead.